"""Forest model generator helpers for Patchworks/Woodstock exports."""

from .patchworks import (
    DEFAULT_CC_MAX_AGE,
    DEFAULT_CC_MIN_AGE,
    DEFAULT_CC_TRANSITION_IFM,
    DEFAULT_FRAGMENTS_CRS,
    DEFAULT_HORIZON_YEARS,
    DEFAULT_IFM_SOURCE_COL,
    DEFAULT_IFM_TARGET_MANAGED_SHARE,
    DEFAULT_IFM_THRESHOLD,
    DEFAULT_SERAL_STAGE_CONFIG_PATH,
    DEFAULT_START_YEAR,
    PatchworksExportResult,
    export_patchworks_package,
    validate_forestmodel_xml_tree,
    validate_fragments_geodataframe,
)
from .adapters import (
    build_bundle_model_context,
    build_bundle_model_context_from_tables,
    normalize_tsa_code,
)
from .core import (
    AnalysisUnitDefinition,
    AttributeBinding,
    BundleModelContext,
    CurveDefinition,
    CurvePoint,
    DefineFieldDefinition,
    ForestModelDefinition,
    SelectDefinition,
    TreatmentAssignment,
    TreatmentDefinition,
)
from .woodstock import (
    DEFAULT_WOODSTOCK_CC_MAX_AGE,
    DEFAULT_WOODSTOCK_CC_MIN_AGE,
    DEFAULT_WOODSTOCK_OUTPUT_DIR,
    WoodstockExportResult,
    export_woodstock_package,
)

__all__ = [
    "DEFAULT_CC_MAX_AGE",
    "DEFAULT_CC_MIN_AGE",
    "DEFAULT_CC_TRANSITION_IFM",
    "DEFAULT_FRAGMENTS_CRS",
    "DEFAULT_HORIZON_YEARS",
    "DEFAULT_IFM_SOURCE_COL",
    "DEFAULT_IFM_THRESHOLD",
    "DEFAULT_IFM_TARGET_MANAGED_SHARE",
    "DEFAULT_SERAL_STAGE_CONFIG_PATH",
    "DEFAULT_START_YEAR",
    "PatchworksExportResult",
    "export_patchworks_package",
    "validate_forestmodel_xml_tree",
    "validate_fragments_geodataframe",
    "CurvePoint",
    "CurveDefinition",
    "AnalysisUnitDefinition",
    "BundleModelContext",
    "DefineFieldDefinition",
    "AttributeBinding",
    "TreatmentAssignment",
    "TreatmentDefinition",
    "SelectDefinition",
    "ForestModelDefinition",
    "normalize_tsa_code",
    "build_bundle_model_context",
    "build_bundle_model_context_from_tables",
    "DEFAULT_WOODSTOCK_CC_MAX_AGE",
    "DEFAULT_WOODSTOCK_CC_MIN_AGE",
    "DEFAULT_WOODSTOCK_OUTPUT_DIR",
    "WoodstockExportResult",
    "export_woodstock_package",
]
